<?php

namespace App\Lib;

class Department {
    private static $depts = array(
        //array('id' => "00", 'name' => "-- Choisir --"),
        array('id' => "01", 'name' => "Ain"),
        array('id' => "02", 'name' => "Aisne"),
        array('id' =>  "03", 'name' => "Allier"),
        array('id' => "04", 'name' => "Alpes de Haute Provence"),
        array('id' => "05", 'name' => "Hautes Alpes"),
        array('id' => "06", 'name' => "Alpes Maritimes"),
        array('id' => "07", 'name' => "Ardèche"),
        array('id' => "08", 'name' => "Ardennes"),
        array('id' => "09", 'name' => "Ariège"),
        array('id' => "10", 'name' => "Aube"),
        array('id' => "11", 'name' => "Aude"),
        array('id' => "12", 'name' => "Aveyron"),
        array('id' => "13", 'name' => "Bouches du Rhône"),
        array('id' => "14", 'name' => "Calvados"),
        array('id' => "15", 'name' => "Cantal"),
        array('id' => "16", 'name' => "Charente"),
        array('id' => "17", 'name' => "Charente Maritime"),
        array('id' => "18", 'name' => "Cher"),
        array('id' => "19", 'name' => "Corrèze"),
        array('id' => "2A", 'name' => "Corse du Sud"),
        array('id' => "2B", 'name' => "Haute Corse"),
        array('id' => "21", 'name' => "Côte d'Or"),
        array('id' => "22", 'name' => "Côtes d'Armor"),
        array('id' => "23", 'name' => "Creuse"),
        array('id' => "24", 'name' => "Dordogne"),
        array('id' => "25", 'name' => "Doubs"),
        array('id' => "26", 'name' => "Drôme"),
        array('id' => "27", 'name' => "Eure"),
        array('id' => "28", 'name' => "Eure et Loire"),
        array('id' => "29", 'name' => "Finistère"),
        array('id' => "30", 'name' => "Gard"),
        array('id' => "31", 'name' => "Haute Garonne"),
        array('id' => "32", 'name' => "Gers"),
        array('id' => "33", 'name' => "Gironde"),
        array('id' => "34", 'name' => "Hérault"),
        array('id' => "35", 'name' => "Ille et Vilaine"),
        array('id' => "36", 'name' => "Indre"),
        array('id' => "37", 'name' => "Indre et Loire"),
        array('id' => "38", 'name' => "Isère"),
        array('id' => "39", 'name' => "Jura"),
        array('id' => "40", 'name' => "Landes"),
        array('id' => "41", 'name' => "Loir et Cher"),
        array('id' => "42", 'name' => "Loire"),
        array('id' => "43", 'name' => "Haute Loire"),
        array('id' => "44", 'name' => "Loire Atlantique"),
        array('id' => "45", 'name' => "Loiret"),
        array('id' => "46", 'name' => "Lot"),
        array('id' => "47", 'name' => "Lot et Garonne"),
        array('id' => "48", 'name' => "Lozère"),
        array('id' => "49", 'name' => "Maine et Loire"),
        array('id' => "50", 'name' => "Manche"),
        array('id' => "51", 'name' => "Marne"),
        array('id' => "52", 'name' => "Haute Marne"),
        array('id' => "53", 'name' => "Mayenne"),
        array('id' => "54", 'name' => "Meurthe et Moselle"),
        array('id' => "55", 'name' => "Meuse"),
        array('id' => "56", 'name' => "Morbihan"),
        array('id' => "57", 'name' => "Moselle"),
        array('id' => "58", 'name' => "Nièvre"),
        array('id' => "59", 'name' => "Nord"),
        array('id' => "60", 'name' => "Oise"),
        array('id' => "61", 'name' => "Orne"),
        array('id' => "62", 'name' => "Pas de Calais"),
        array('id' => "63", 'name' => "Puy de Dôme"),
        array('id' => "64", 'name' => "Pyrénées Atlantiques"),
        array('id' => "65", 'name' => "Hautes Pyrénées"),
        array('id' => "66", 'name' => "Pyrénées Orientales"),
        array('id' => "67", 'name' => "Bas Rhin"),
        array('id' => "68", 'name' => "Haut Rhin"),
        array('id' => "69", 'name' => "Rhône"),
        array('id' => "70", 'name' => "Haute Saône"),
        array('id' => "71", 'name' => "Saône et Loire"),
        array('id' => "72", 'name' => "Sarthe"),
        array('id' => "73", 'name' => "Savoie"),
        array('id' => "74", 'name' => "Haute Savoie"),
        array('id' => "75", 'name' => "Paris"),
        array('id' => "76", 'name' => "Seine Maritime"),
        array('id' => "77", 'name' => "Seine et Marne"),
        array('id' => "78", 'name' => "Yvelines"),
        array('id' => "79", 'name' => "Deux Sèvres"),
        array('id' => "80", 'name' => "Somme"),
        array('id' => "81", 'name' => "Tarn"),
        array('id' => "82", 'name' => "Tarn et Garonne"),
        array('id' => "83", 'name' => "Var"),
        array('id' => "84", 'name' => "Vaucluse"),
        array('id' => "85", 'name' => "Vendée"),
        array('id' => "86", 'name' => "Vienne"),
        array('id' => "87", 'name' => "Haute Vienne"),
        array('id' => "88", 'name' => "Vosges"),
        array('id' => "89", 'name' => "Yonne"),
        array('id' => "90", 'name' => "Territoire de Belfort"),
        array('id' => "91", 'name' => "Essonne"),
        array('id' => "92", 'name' => "Hauts de Seine"),
        array('id' => "93", 'name' => "Seine St Denis"),
        array('id' => "94", 'name' => "Val de Marne"),
        array('id' => "95", 'name' => "Val d'Oise"),
        array('id' => "97", 'name' => "DOM"),
    );
    
    public static function getAll() {
        return self::$depts;
    }
}