<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250905124350 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mobile_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(120) NOT NULL, step INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, participant_id INT NOT NULL, escape_game_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D49E81135F37A13B ON mobile_link (token)');
        $this->addSql('CREATE INDEX IDX_D49E81139D1C3019 ON mobile_link (participant_id)');
        $this->addSql('CREATE INDEX IDX_D49E8113535D9AB ON mobile_link (escape_game_id)');
        $this->addSql('CREATE INDEX IDX_D49E81135F37A13B ON mobile_link (token)');
        $this->addSql('ALTER TABLE mobile_link ADD CONSTRAINT FK_D49E81139D1C3019 FOREIGN KEY (participant_id) REFERENCES aff_participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mobile_link ADD CONSTRAINT FK_D49E8113535D9AB FOREIGN KEY (escape_game_id) REFERENCES aff_escapegame (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mobile_link DROP CONSTRAINT FK_D49E81139D1C3019');
        $this->addSql('ALTER TABLE mobile_link DROP CONSTRAINT FK_D49E8113535D9AB');
        $this->addSql('DROP TABLE mobile_link');
    }
}
