<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251009123451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE escape_workshop_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(120) NOT NULL, code VARCHAR(16) NOT NULL, is_master BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E770467471F7E88B ON escape_workshop_session (event_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_escape_workshop_code ON escape_workshop_session (code)');
        $this->addSql('ALTER TABLE escape_workshop_session ADD CONSTRAINT FK_E770467471F7E88B FOREIGN KEY (event_id) REFERENCES aff_postevent (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escapegame ADD workshop_session_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE aff_escapegame ADD CONSTRAINT FK_978C3950E6C175BA FOREIGN KEY (workshop_session_id) REFERENCES escape_workshop_session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_978C3950E6C175BA ON aff_escapegame (workshop_session_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE escape_workshop_session DROP CONSTRAINT FK_E770467471F7E88B');
        $this->addSql('DROP TABLE escape_workshop_session');
        $this->addSql('ALTER TABLE aff_escapegame DROP CONSTRAINT FK_978C3950E6C175BA');
        $this->addSql('DROP INDEX IDX_978C3950E6C175BA');
        $this->addSql('ALTER TABLE aff_escapegame DROP workshop_session_id');
    }
}
