<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251121163622 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE aff_escape_team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, avatar_key VARCHAR(64) NOT NULL, color VARCHAR(16) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, run_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1614EFF384E3FEC4 ON aff_escape_team (run_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_escape_team_run_name ON aff_escape_team (run_id, name)');
        $this->addSql('CREATE TABLE aff_escape_team_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nickname VARCHAR(80) NOT NULL, avatar_key VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB41ADE9296CD8AE ON aff_escape_team_member (team_id)');
        $this->addSql('CREATE TABLE aff_escape_team_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, hero_image_url VARCHAR(255) DEFAULT NULL, share_slug VARCHAR(120) NOT NULL, status VARCHAR(24) NOT NULL, max_teams INT DEFAULT 10 NOT NULL, time_limit_seconds INT DEFAULT NULL, registration_opened_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, escape_game_id INT NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F10AF1EA535D9AB ON aff_escape_team_run (escape_game_id)');
        $this->addSql('CREATE INDEX IDX_F10AF1EA7E3C61F9 ON aff_escape_team_run (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_escape_team_run_slug ON aff_escape_team_run (share_slug)');
        $this->addSql('CREATE TABLE aff_escape_team_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, progress JSON DEFAULT NULL, step_states JSON DEFAULT NULL, hints_used INT NOT NULL, duration_ms INT NOT NULL, current_step INT DEFAULT NULL, completed BOOLEAN NOT NULL, penalties INT DEFAULT 0 NOT NULL, final_answer VARCHAR(190) DEFAULT NULL, secret_code VARCHAR(190) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, run_id INT NOT NULL, team_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57E7D35184E3FEC4 ON aff_escape_team_session (run_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57E7D351296CD8AE ON aff_escape_team_session (team_id)');
        $this->addSql('ALTER TABLE aff_escape_team ADD CONSTRAINT FK_1614EFF384E3FEC4 FOREIGN KEY (run_id) REFERENCES aff_escape_team_run (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team_member ADD CONSTRAINT FK_DB41ADE9296CD8AE FOREIGN KEY (team_id) REFERENCES aff_escape_team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team_run ADD CONSTRAINT FK_F10AF1EA535D9AB FOREIGN KEY (escape_game_id) REFERENCES aff_escapegame (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team_run ADD CONSTRAINT FK_F10AF1EA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES aff_participant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team_session ADD CONSTRAINT FK_57E7D35184E3FEC4 FOREIGN KEY (run_id) REFERENCES aff_escape_team_run (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team_session ADD CONSTRAINT FK_57E7D351296CD8AE FOREIGN KEY (team_id) REFERENCES aff_escape_team (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE aff_escape_team DROP CONSTRAINT FK_1614EFF384E3FEC4');
        $this->addSql('ALTER TABLE aff_escape_team_member DROP CONSTRAINT FK_DB41ADE9296CD8AE');
        $this->addSql('ALTER TABLE aff_escape_team_run DROP CONSTRAINT FK_F10AF1EA535D9AB');
        $this->addSql('ALTER TABLE aff_escape_team_run DROP CONSTRAINT FK_F10AF1EA7E3C61F9');
        $this->addSql('ALTER TABLE aff_escape_team_session DROP CONSTRAINT FK_57E7D35184E3FEC4');
        $this->addSql('ALTER TABLE aff_escape_team_session DROP CONSTRAINT FK_57E7D351296CD8AE');
        $this->addSql('DROP TABLE aff_escape_team');
        $this->addSql('DROP TABLE aff_escape_team_member');
        $this->addSql('DROP TABLE aff_escape_team_run');
        $this->addSql('DROP TABLE aff_escape_team_session');
    }
}
