<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250911140512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agenda_enrollments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id UUID NOT NULL, participant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7F0421F471F7E88B ON agenda_enrollments (event_id)');
        $this->addSql('CREATE INDEX IDX_7F0421F49D1C3019 ON agenda_enrollments (participant_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7F0421F471F7E88B9D1C3019 ON agenda_enrollments (event_id, participant_id)');
        $this->addSql('CREATE TABLE agenda_events (id UUID NOT NULL, slug VARCHAR(160) NOT NULL, title VARCHAR(140) NOT NULL, description TEXT DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, timezone VARCHAR(64) NOT NULL, is_all_day BOOLEAN NOT NULL, location_name VARCHAR(120) DEFAULT NULL, location_address VARCHAR(250) DEFAULT NULL, capacity INT DEFAULT NULL, visibility VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, published BOOLEAN NOT NULL, category VARCHAR(48) NOT NULL, source_type VARCHAR(48) DEFAULT NULL, source_id VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organizer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4460D15D989D9B62 ON agenda_events (slug)');
        $this->addSql('CREATE INDEX IDX_4460D15D876C4DDA ON agenda_events (organizer_id)');
        $this->addSql('CREATE INDEX IDX_4460D15D55A0507C ON agenda_events (starts_at)');
        $this->addSql('CREATE INDEX IDX_4460D15D683C6017518E4300 ON agenda_events (published, visibility)');
        $this->addSql('ALTER TABLE agenda_enrollments ADD CONSTRAINT FK_7F0421F471F7E88B FOREIGN KEY (event_id) REFERENCES agenda_events (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agenda_enrollments ADD CONSTRAINT FK_7F0421F49D1C3019 FOREIGN KEY (participant_id) REFERENCES aff_participant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agenda_events ADD CONSTRAINT FK_4460D15D876C4DDA FOREIGN KEY (organizer_id) REFERENCES aff_participant (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agenda_enrollments DROP CONSTRAINT FK_7F0421F471F7E88B');
        $this->addSql('ALTER TABLE agenda_enrollments DROP CONSTRAINT FK_7F0421F49D1C3019');
        $this->addSql('ALTER TABLE agenda_events DROP CONSTRAINT FK_4460D15D876C4DDA');
        $this->addSql('DROP TABLE agenda_enrollments');
        $this->addSql('DROP TABLE agenda_events');
    }
}
