<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250914153229 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ar_scene (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, mind_target_path VARCHAR(255) DEFAULT NULL, target_index INT NOT NULL, model_url VARCHAR(255) NOT NULL, sound_url VARCHAR(255) DEFAULT NULL, owner_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE aff_escapegame DROP COLUMN universe');
        $this->addSql('ALTER TABLE aff_escapegame RENAME COLUMN univers TO universe');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE ar_scene');
        $this->addSql("ALTER TABLE aff_escapegame ADD universe TEXT DEFAULT NULL");
        $this->addSql('ALTER TABLE aff_escapegame RENAME COLUMN universe TO univers');
    }
}
