<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251219151911 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE aff_escape_team_qr_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, run_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B540523684E3FEC4 ON aff_escape_team_qr_group (run_id)');
        $this->addSql('CREATE TABLE aff_escape_team_qr_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, team_name VARCHAR(120) NOT NULL, identification_code VARCHAR(8) NOT NULL, message VARCHAR(255) NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_99379F885F37A13B ON aff_escape_team_qr_page (token)');
        $this->addSql('CREATE INDEX IDX_99379F88FE54D947 ON aff_escape_team_qr_page (group_id)');
        $this->addSql('CREATE INDEX IDX_99379F885F37A13B ON aff_escape_team_qr_page (token)');
        $this->addSql('ALTER TABLE aff_escape_team_qr_group ADD CONSTRAINT FK_B540523684E3FEC4 FOREIGN KEY (run_id) REFERENCES aff_escape_team_run (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team_qr_page ADD CONSTRAINT FK_99379F88FE54D947 FOREIGN KEY (group_id) REFERENCES aff_escape_team_qr_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aff_escape_team ADD qr_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE aff_escape_team ADD CONSTRAINT FK_1614EFF3900AE1F3 FOREIGN KEY (qr_group_id) REFERENCES aff_escape_team_qr_group (id)');
        $this->addSql('CREATE INDEX IDX_1614EFF3900AE1F3 ON aff_escape_team (qr_group_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE aff_escape_team_qr_group DROP CONSTRAINT FK_B540523684E3FEC4');
        $this->addSql('ALTER TABLE aff_escape_team_qr_page DROP CONSTRAINT FK_99379F88FE54D947');
        $this->addSql('DROP TABLE aff_escape_team_qr_group');
        $this->addSql('DROP TABLE aff_escape_team_qr_page');
        $this->addSql('ALTER TABLE aff_escape_team DROP CONSTRAINT FK_1614EFF3900AE1F3');
        $this->addSql('DROP INDEX IDX_1614EFF3900AE1F3');
        $this->addSql('ALTER TABLE aff_escape_team DROP qr_group_id');
    }
}
